### ISSUE TITLE
Default values with inner structs don't seem to be working properly

### ISSUE THREAD

**Issue by pragmaticivan** [caarlos0/env#193] opened 2021-10-09 19:04 UTC
```go
type AppConfig struct {
	Web struct {
		APIHost         string        `env:"API_HOST" envDefault:"0.0.0.0:3000"`
		DebugHost       string        `env:"DEBUG_HOST" envDefault:"0.0.0.0:4000"`
		ReadTimeout     time.Duration `env:"READ_TIMEOUT" envDefault:"5s"`
		WriteTimeout    time.Duration `env:"WRITE_TIMEOUT" envDefault:"10s"`
		IdleTimeout     time.Duration `env:"IDLE_TIMEOUT" envDefault:"120s"`
		ShutdownTimeout time.Duration `env:"SHUTDOWN_TIMEOUT" envDefault:"20s"`
	}
	Db struct {
		Username string `env:"DB_USERNAME" envDefault:"foo"`
	}
}
```

```go
  cfg := config.AppConfig{}

  if err := env.Parse(&cfg); err != nil {
      fmt.Printf("%+v\n", err)
  }
  fmt.Printf("%+v\n", cfg)
>>>> {Web:{APIHost: DebugHost: ReadTimeout:0s WriteTimeout:0s IdleTimeout:0s ShutdownTimeout:0s} Db:{Username:}}
  fmt.Println(cfg.Db.Username)
>>>>
```

Notes:
* Inner Structs are intentionally not pointers.

**Comment by Oppodelldog** [comment] 2021-10-15 17:54
I tried to reproduce, but the data is filled properly. 
@pragmaticivan please have a look https://play.golang.org/p/_Hk-dl4vVps

**Comment by caarlos0** [comment] 2021-10-15 19:14
as pointed out by @Oppodelldog , it is working...

maybe you have a DB_USERNAME env set to an empty string?

in any case, not a bug, closing

**Closed by caarlos0** 2021-10-15 19:14 UTC
